behaviors:
  PlanarConstruction:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 4096
      learning_rate: 0.00035
      beta: 0.0025
      epsilon: 0.4
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
    keep_checkpoints: 8
    max_steps: 50000000
    time_horizon: 256
    summary_freq: 10000
    threaded: True

environment_parameters:
  min_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 4.0
      - name: Lesson3
        value: 6.0
  max_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 2.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 4.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 8.0
      - name: Lesson3
        value: 12.0
  distance_threshold:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.1
          require_reset: true
        value: 30.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.2
          require_reset: true
        value: 22.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 15.0
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.7
        value: 8.0
      - name: Lesson4
        value: 6.0