behaviors:
  PlanarConstruction:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 48000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: True
environment_parameters:
  min_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: minPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          require_reset: true
        value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: minPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: minPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 4.0
      - name: Lesson3
        value: 6.0
  max_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: maxPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          require_reset: true
        value: 2.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: maxPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 4.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: maxPucks
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 8.0
      - name: Lesson3
        value: 12.0
  distance_threshold:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: distanceThreshold
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
          require_reset: true
        value: 10.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: distanceThreshold
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 8.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: distanceThreshold
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.7
        value: 6.0
      - name: Lesson3
        value: 4.0