behaviors:
  PlanarConstruction:
    trainer_type: poca
    hyperparameters:
      batch_size: 2028
      buffer_size: 16384
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 10000
    threaded: True

environment_parameters:
  min_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 1.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 2.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 2.0
      - name: Lesson3
        value: 2.0
  max_pucks:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 2.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 4.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 4.0
      - name: Lesson3
        value: 4.0
  distance_threshold:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.2
          require_reset: true
        value: 33.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
          require_reset: true
        value: 28.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.6
        value: 22.0
      - name: Lesson3
        completion_criteria:
          measure: progress
          behavior: PlanarConstruction
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.8
        value: 15.0
      - name: Lesson4
        value: 8.0